# Generated by Django 3.0.3 on 2020-02-27 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('number', models.IntegerField()),
                ('owner', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fromAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_from', to='transactions.Account')),
                ('toAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_to', to='transactions.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
